### ISSUE TITLE
Missing source code for TournamentModule.dll for BWAPI version 4.2.0

### ISSUE THREAD

**Issue by chriscoxe** [davechurchill/StarcraftAITournamentManager#12]
The source code is missing for TournamentModule.dll for BWAPI version 4.2.0, i.e. the file bwapi-data/TournamentModule.dll contained in server/required/Required_BWAPI_420.zip. For the other versions it is located at e.g. src/tournamentmodule/BWAPI_412

Please could it be added? The reasons are for transparency and because I would like to build my own variant of TournamentModule.dll for BWAPI 4.2.0 that runs on Windows XP SP3 (FYI, BWAPI 4.2.0 doesn't work on Windows XP SP3 and I've already proposed a fix to BWAPI in https://github.com/bwapi/bwapi/issues/733).  Thanks

**Comment by davechurchill** [comment]
I believe it's identical to the 4.1.2 version, just compiled in 4.2.0, but @richard-kelly could you add it?

**Comment by richard-kelly** [comment]
@davechurchill that's correct. I'll create a version named 4.2.0 for clarity.

**Comment by chriscoxe** [comment]
Thanks, please feel free to close this issue.  I just successfully used it to build and test my own variant of TournamentModule.dll for a modified version of BWAPI 4.2.0 that runs on Windows XP SP3.

Note: the injectory.x86.exe file included in StarcraftAITournamentManager doesn't run on Windows XP SP3 (due to the same issue described in https://github.com/bwapi/bwapi/issues/733) but I was able to use Chaoslauncher instead with an old version of the StarcraftAITournamentManager JAR files.

**Comment by davechurchill** [comment]
We should just update the instructions to say Windows 7

**Comment by chriscoxe** [comment]
Sorry, closed by misclick.

**Comment by chriscoxe** [comment]
By the way, the stuff about Windows XP SP3 was just FYI - I wasn't pushing for Windows XP SP3 support.

**Comment by davechurchill** [comment]
I just think that advertising Windows 7 is the easiest option rather than worrying about XP versioning :)

**Comment by davechurchill** [comment]
@richard-kelly Has this been added? If so can you close the issue

**Comment by richard-kelly** [comment]
Yes, the change was made.
