### ISSUE TITLE
problems of psexec

### ISSUE THREAD

**Issue by sijiaxu** [davechurchill/StarcraftAITournamentManager#19]
I use the psexec script in the document to launch client at different machine,
but it seems only launch the process at back-end, when I remote login the target machine, I can not see the client is running and the client exit after a short time.....

**Comment by richard-kelly** [comment]
The -i option to psexec is supposed to make it launch normally. Make sure all quotes are included as in the instructions. Figuring out that command took some trial and error, and it worked going from Windows 10 (shouldn't matter) to a Windows 7 client. There may be some other requirements for the remote machine for PsExec to work properly. If the client is exiting quickly it might be a problem with the client settings. If the settings argument is incorrect or the settings file doesn't parse as JSON, or it has another error it would terminate quickly.

**Comment by davechurchill** [comment]
Keep note all this can be done without psexec, it's just for convenience of
updating and starting clients

**Comment by davechurchill** [comment]
Since this is not an issue with the TM software I will close the issue, but feel free to continue the conversation
