### ISSUE TITLE
support of machine learning library

### ISSUE THREAD

**Issue by sijiaxu** [davechurchill/StarcraftAITournamentManager#20]
because it is much more efficient to use other language(ie. python) to write some machine learning code on top of some library(ie. tensorflow), but the official AIIDE tournament machine seems do not support such python library.
so I has several questions:
1. do you have plan to do such things in future?
2. is the submitted AI folder has space limitation? for example, can i put a pre-config python version in the AI folder which may occupy about 30m.
3. other recommended alternative?

@davechurchill @richard-kelly 

Thanks

**Comment by davechurchill** [comment]
Nothing stops you from running machine learning software on any of the client machines. In fact, we supported it for the tournament this year - we just don't include those libraries with the tournament software since it would be too difficult to keep track of all the different libraries. Once you install the libraries on the machine, just modify the bot launch batch file to run whatever python you need on the client machine and it should work just fine.

**Comment by sijiaxu** [comment]
ok，do you mean I should submit the bot with a  pre-configured python version which can install on the tournament machine only once?
By the way, which bot this year used this pre-install function?

**Comment by davechurchill** [comment]
You write the code - we will provide the libraries. So you would say "this program requires python 3.6.x and tensorflow installed" and we will install those libraries

**Comment by sijiaxu** [comment]
oh，that's great!
Thanks

**Comment by davechurchill** [comment]
If you look at the 'compete' page on the website: http://www.cs.mun.ca/~dchurchill/starcraftaicomp/compete.shtml

It says your submission must include:

"A readme file containing compilation instructions, including any environment variables or external libraries (boost, etc) used in your bot, with links to the official download pages for those libraries (we will have the latest version of boost and all versions of BWAPI installed)"

So as long as you tell us with your submission which libraries or software packages you need, and you give us an official release version to run, it's fine.
