### ISSUE TITLE
1 vs N tournament 

### ISSUE THREAD

**Issue by sijiaxu** [davechurchill/StarcraftAITournamentManager#21]
Hi,

I notice that when the tournament type set to 1vsN, the schedule of the tournament is not paralleling even though I have enough machines.
for example, there are three bots : A, B, C the schedule is sequential :
A-B
A-C
not A-B and A-C holding on four different machines.

as far as I know, paralleling the game for each round may satisfy current AIIDE rules, so is there some settings which I missed to achieve this...

**Comment by davechurchill** [comment]
It may be that it's waiting to copy over the learning data

@richard-kelly Does the TM consider each game a 'round' for the 1vN? If so we should probably change it

**Comment by sijiaxu** [comment]
I find the reason is client's starcraft process is not start normally, it is not the rare case, so the overall schedule seems to be sequential.

on my Win7 VMs, I manually start two clients on two different machines,  when the client execute: 
cd /D C:\TM\Starcraft\ & injectory.x86.exe --launch StarCraft.exe --inject bwapi-data\BWAPI.dll --set-flags SEM_NOGPFAULTERRORBOX
the starcraft process can be seen at task manger, but the starcraft GUI is not appearing at the frontend.
so after 60 seconds, the client close current match.
this situation happens occasionally, I also notice that when a client has launched correctly once, it will behave normally since then.

by the way,  when I start a separate cmd window, and type the above command, the starcraft client always launch normally at the frontend.

any idea about this situations?

**Comment by richard-kelly** [comment]
@sijiaxu If I understand your problem (from first post in this issue) you're right, there's a setting for this. You're saying that in a 3-bot 1vall tournament the server is waiting for A-B and A-C to finish before starting any more matches?

Previously it behaved the way you expected just based on whether it was allvall or 1vall, but we saw the need to sometimes wait for 'round' completion (in this case A vs all the other bots on one map) for testing learning for the 'A' bot. Set `enableBotFileIO = false ` in the server settings and it will play as many games as possible without pausing.

**Comment by sijiaxu** [comment]
@richard-kelly ok, I got it.  Thanks!
the second problems is some weird things related to my VM, not the TM, so I close this issue.

**Comment by richard-kelly** [comment]
@sijiaxu I have had weird issues where StarCraft would only start if I tried to start it twice, whether normally or with injectory. So the TM client was never able to start games, I think. Whenever that happened it was resolved by restarting the VMs, so I've never figured out the cause.

**Comment by sijiaxu** [comment]
@richard-kelly yes, Thanks a lot, I also resolve this issue by restarting the VM, then everything works fine.
