### ISSUE TITLE
TM overwrites bwapi.ini

### ISSUE THREAD

**Issue by NiteKat** [davechurchill/StarcraftAITournamentManager#22]
The TM spits out a hard coded BWAPI.ini, so if you want to do something like have the sound turned on, you can't edit the bwapi.ini file in the required folders. If you do, the clients will still get stuck with the hard coded bwapi from the TM (this prevents changing any other settings for the .ini file too).

**Comment by davechurchill** [comment]
This is by design, since we want to make 100% sure that the BWAPI settings are changed specifically for each game. If you want, you can request a specific feature be added to the settings file, but as long as BWAPI uses the ini file, this won't change.
