### ISSUE TITLE
some confusing problems

### ISSUE THREAD

**Issue by yuntao-ma** [davechurchill/StarcraftAITournamentManager#35]
We tried to run the Starcraft AI Tournament Manager and we encountered some problems which make us confused.
1. We added some bots of AIIDE2018 to the competition and modified server_settings.json as stated, but some bots didn’t do any action in some specific games( such as Locutus vs. CSE, Locutus didn’t do anything) when they act normal in other games.
2.   When the game of Cherrypi begins, the starcraft will crash and has no response.

**Comment by richard-kelly** [comment]
Some of the bots have special requirements, there were several in the 2018 tournament. Cherrypi needs CUDA installed, version 9.0 (and corresponding CuDNN). Also the final version of CherryPi was DLL based, for the settings.json file.

I'm not sure what the Locutus/CSE issue could be. How many client machines are you using? I'd check that it isn't just happening on certain machine/bot combinations. Is there an error printed on the game screen (just after game start) about the DLL not loading?

**Comment by richard-kelly** [comment]
Also, some of the large DLLs from Cherrypi can be copied into the Starcraft directory (and removed from the Cherrypi AI dir) so that the tournament manager doesn't have to transfer them every time.

**Comment by yuntao-ma** [comment]
2 clients. Nothing printed on the game screen.

**Comment by yuntao-ma** [comment]
Sorry. I didn't notice it. There is an error printed on the game screen "ERROR: Failed to load the AI Module "bwapi-data\AI\Locutus.dll" ".
