### ISSUE TITLE
Use the latest Microsoft Visual C++ x86 redistributables

### ISSUE THREAD

**Issue by chriscoxe** [davechurchill/StarcraftAITournamentManager#36]
Update the installer for the Microsoft Visual C++ x86 redistributables (README.md has links to http://www.cs.mun.ca/~dchurchill/starcraftaicomp/all_vcredist_x86.zip) to use the latest versions of the redistributables.  The reasons are to ensure StarcraftAITournamentManager is compatible with BWAPI 4.4.0, and with bots that use BWAPI < 4.4.0 but updated compiler versions, and because it may fix some crashes and security vulnerabilities for old bots (Microsoft updated some old redists to fix some crashes in MFC).

**Comment by chriscoxe** [comment]
I have got updated redists from https://support.microsoft.com/en-au/help/2977003/the-latest-supported-visual-c-downloads, removed the unnecessary versions (versions that would get overwritten by later versions), appended version number to each filename, renamed the BAT filename from "intall_all_redist.bat" to "install_redists.bat" and edited its content accordingly, created a new ZIP file from the files, and tested installing it on a Windows 7 SP1 VM by manually uninstalling all restributables then starting a command prompt as an Administrator then running the BAT file.

Notes:
* For the best compatibility with all old bots, all these redists should be installed. I.E. not just the highest version out of the vs2018 ones, and not just the highest version out of the vs2013 ones.
* vs2008_vcredist_x86-9.0.30729.6161.exe's file properties say that the version is 9.0.30729.5677 but its version is actually shown as 9.0.30729.6161 in Control Panel -> Add/Remove programs.
* The ".8", ".17", ".325" parts of the particular version numbers do not show up in Control Panel -> Add/Remove programs, but I've included them in the filename anyway for clarity.
* The extra underscore character in "vs2017_vc_redist.x86" is not a typo - Microsoft changed it's name from "vcredist.x86.exe" to "vc_redist.x86.exe".
* I deleted the redist for VS2015 because according to Microsoft, if you are installing the (x86) VS2017 redist, you don't need the (x86) VS2015 redist, and it would be overwritten anyway when you install the (x86) redist for VS2017.

**Comment by chriscoxe** [comment]
To ensure trustworthiness, you can download the redists from Microsoft yourself and rename them to include version numbers so that the BAT file will work, but for your convenience, I have attached them below.  Sorry, rather than simply attaching a new all_vcredist_x86.zip file, I had to attach each file individually as a ZIP file because GitHub wouldn't let me upload one big file or BAT/EXE files.  Please unzip them, delete the ZIPs, then create a new all_vcredist_x86.zip.
[install_redists.bat.zip](https://github.com/davechurchill/StarcraftAITournamentManager/files/3018015/install_redists.bat.zip)
[vs2008_vcredist_x86-9.0.21022.8.exe.zip](https://github.com/davechurchill/StarcraftAITournamentManager/files/3018019/vs2008_vcredist_x86-9.0.21022.8.exe.zip)
[vs2008_vcredist_x86-9.0.30729.17.exe.zip](https://github.com/davechurchill/StarcraftAITournamentManager/files/3018021/vs2008_vcredist_x86-9.0.30729.17.exe.zip)
[vs2008_vcredist_x86-9.0.30729.6161.exe.zip](https://github.com/davechurchill/StarcraftAITournamentManager/files/3018032/vs2008_vcredist_x86-9.0.30729.6161.exe.zip)
[vs2010_vcredist_x86-10.0.40219.325.exe.zip](https://github.com/davechurchill/StarcraftAITournamentManager/files/3018035/vs2010_vcredist_x86-10.0.40219.325.exe.zip)
[vs2012_vcredist_x86-11.0.61030.0.exe.zip](https://github.com/davechurchill/StarcraftAITournamentManager/files/3018043/vs2012_vcredist_x86-11.0.61030.0.exe.zip)
[vs2013_vcredist_x86-12.0.30501.0.exe.zip](https://github.com/davechurchill/StarcraftAITournamentManager/files/3018053/vs2013_vcredist_x86-12.0.30501.0.exe.zip)
[vs2013_vcredist_x86-12.0.40660.0.exe.zip](https://github.com/davechurchill/StarcraftAITournamentManager/files/3018060/vs2013_vcredist_x86-12.0.40660.0.exe.zip)
[vs2017_vc_redist.x86-14.16.27027.1.exe.zip](https://github.com/davechurchill/StarcraftAITournamentManager/files/3018071/vs2017_vc_redist.x86-14.16.27027.1.exe.zip)

MD5 for ZIPs:
ae315f69233690f7064c29f523f28b2d *install_redists.bat.zip
621e520ed120a635575b2fd9eb7c0948 *vs2008_vcredist_x86-9.0.21022.8.exe.zip
7295ce866c7cfc0f829ee70dd37bf212 *vs2008_vcredist_x86-9.0.30729.17.exe.zip
446fcb7c5e96f0db11a5bfdf5c8a4600 *vs2008_vcredist_x86-9.0.30729.6161.exe.zip
3cc2d5cbc7bf81cd9d0a67c7588a14e9 *vs2010_vcredist_x86-10.0.40219.325.exe.zip
3011b8df456f197466e4c23626e3e001 *vs2012_vcredist_x86-11.0.61030.0.exe.zip
eae8d4b35f850865e28c0ddaa101caf9 *vs2013_vcredist_x86-12.0.30501.0.exe.zip
6390b07fd195026e264c7bbd41b1aad7 *vs2013_vcredist_x86-12.0.40660.0.exe.zip
7df03cc486f0478134282a6e020f4b41 *vs2017_vc_redist.x86-14.16.27027.1.exe.zip

SHA256 for ZIPs:
a9175d2fcbcf638bd26fffa9c6f3bdd61a938c0c33b8c482ca40661526e79a82 *install_redists.bat.zip
e2039e6e6f7e957e6a0f930319d199a9b6722a1791b8170386a3524c1203411a *vs2008_vcredist_x86-9.0.21022.8.exe.zip
520345c1412cd317f451569d4f65886a36b98e64f979d319522490e10859d91c *vs2008_vcredist_x86-9.0.30729.17.exe.zip
caeb12d8ffc119f6965003fc0e6e0c0341293233b812acb78192de73ac3202c2 *vs2008_vcredist_x86-9.0.30729.6161.exe.zip
2cb4b367d96f8f8decf69f556dfcf1b36fd95ad8680fe36a97d22c907ea58a4c *vs2010_vcredist_x86-10.0.40219.325.exe.zip
1456a9b0e9096b724af1d586dbc4bfc1f760b07a5747a4f15b5b9cbcc61f84f6 *vs2012_vcredist_x86-11.0.61030.0.exe.zip
f2d88480ba570d4a4adb26afa519b4bccb6f661c50524e7e8d4e335209275bf8 *vs2013_vcredist_x86-12.0.30501.0.exe.zip
106838c06f0225777959c9390f06fc4e843c593c8bdf6c6ca380e85c3f89b197 *vs2013_vcredist_x86-12.0.40660.0.exe.zip
53906cd28ce4398fcc6dd4316cecd1f7ad572d130eb8d64ca7a6025019dec0cb *vs2017_vc_redist.x86-14.16.27027.1.exe.zip

MD5 for EXEs:
b936f0f378b9a35489353e878154e899 *vs2008_vcredist_x86-9.0.21022.8.exe
5689d43c3b201dd3810fa3bba4a6476a *vs2008_vcredist_x86-9.0.30729.17.exe
35da2bf2befd998980a495b6f4f55e60 *vs2008_vcredist_x86-9.0.30729.6161.exe
1801436936e64598bab5b87b37dc7f87 *vs2010_vcredist_x86-10.0.40219.325.exe
7f52a19ecaf7db3c163dd164be3e592e *vs2012_vcredist_x86-11.0.61030.0.exe
0fc525b6b7b96a87523daa7a0013c69d *vs2013_vcredist_x86-12.0.30501.0.exe
7ab4b27f110c5fe933c45ea1fed7a329 *vs2013_vcredist_x86-12.0.40660.0.exe
08d7a23f1a537867d862abd72ec407c9 *vs2017_vc_redist.x86-14.16.27027.1.exe

SHA256 for EXEs:
c6a7e484f4d84883bc1205bccea3114c0521025712922298ede9b2a1cd632357 *vs2008_vcredist_x86-9.0.21022.8.exe
41f45a46ee56626ff2699d525bb56a3bb4718c5ca5f4fb5b3b38add64584026b *vs2008_vcredist_x86-9.0.30729.17.exe
6b3e4c51c6c0e5f68c8a72b497445af3dbf976394cbb62aa23569065c28deeb6 *vs2008_vcredist_x86-9.0.30729.6161.exe
67313b3d1bc86e83091e8de22981f14968f1a7fb12eb7ad467754c40cd94cc3d *vs2010_vcredist_x86-10.0.40219.325.exe
b924ad8062eaf4e70437c8be50fa612162795ff0839479546ce907ffa8d6e386 *vs2012_vcredist_x86-11.0.61030.0.exe
a22895e55b26202eae166838edbe2ea6aad00d7ea600c11f8a31ede5cbce2048 *vs2013_vcredist_x86-12.0.30501.0.exe
89f4e593ea5541d1c53f983923124f9fd061a1c0c967339109e375c661573c17 *vs2013_vcredist_x86-12.0.40660.0.exe
7355962b95d6a5441c304cd2b86baf37bc206f63349f4a02289bcfb69ef142d3 *vs2017_vc_redist.x86-14.16.27027.1.exe

**Comment by chriscoxe** [comment]
Please could someone have a look?  Contestants will be able to submit bots to CoG(/CIG) 2019 from Monday (17th June) until 10th July and may want to check that their bots work properly in StarcraftAITournamentManager before they submit.

**Comment by chriscoxe** [comment]
The redists at  https://support.microsoft.com/en-au/help/2977003/the-latest-supported-visual-c-downloads have been updated again...

**Comment by richard-kelly** [comment]
So @chriscoxe should the new versions be included in addition to the ones in your bat file above? How did you come up with that list? (I'm assuming there are more than two versions of the 2013 redist, for example)

**Comment by chriscoxe** [comment]
When you install a particular redist version, depending on which versions you already have installed, in some cases it overwrites an existing installed version (and updates its version number to the new version number) and in some cases it installs a separate additional new version.  To come up with the list in my previous post and the new list below, a long time ago, I started with the ZIP file from Dave's website, merged his new list into mine whenever he changed his ZIP file, and I occasionally updated my list to include additional new versions that I noticed Microsoft had released that I needed to get various other people's bots working on my machine.  It is true that there may be other old versions that I wasn't aware of and missed that don't get overwritten when you install the ones in my new list.  I don't know whether this is a problem or not, but I have run a wide variety of bots (until about 2017 anyway) and my list seems to be all the ones I needed.

I have just gone through https://support.microsoft.com/en-au/help/2977003/the-latest-supported-visual-c-downloads to see which have changed.  When updating the ZIP file on the AIIDE website, I suggest also adding a link to that Microsoft page alongside the ZIP file download.  At present, the only differences compared to my previous post are that vs2013_vcredist_x86-12.0.40660.0.exe is replaced by vs2013_vcredist_x86-12.0.40664.0.exe, and vs2017_vc_redist.x86-14.16.27027.1.exe is replaced by vs2015-2019_vc_redist.x86-14.21.27702.2.exe (and Microsoft are now naming this one "2015-2019" in the product name whereas the previous one was named just "2017").  I have uninstalled all of the ones from my last post, downloaded the new ones, removed the ones from my list that were replaced, updated install_redists.bat accordingly then tested that the new install_redists.bat runs fine (as Administrator) and that I can see all the new list of versions in Start -> Control Panel -> Programs -> Programs and Features.  I haven't run any bots though.  Here is the new complete list of files.

[install_redists.bat.zip](https://github.com/davechurchill/StarcraftAITournamentManager/files/3289034/install_redists.bat.zip)
[vs2008_vcredist_x86-9.0.21022.8.exe.zip](https://github.com/davechurchill/StarcraftAITournamentManager/files/3288968/vs2008_vcredist_x86-9.0.21022.8.exe.zip)
[vs2008_vcredist_x86-9.0.30729.17.exe.zip](https://github.com/davechurchill/StarcraftAITournamentManager/files/3288969/vs2008_vcredist_x86-9.0.30729.17.exe.zip)
[vs2008_vcredist_x86-9.0.30729.6161.exe.zip](https://github.com/davechurchill/StarcraftAITournamentManager/files/3288970/vs2008_vcredist_x86-9.0.30729.6161.exe.zip)
[vs2010_vcredist_x86-10.0.40219.325.exe.zip](https://github.com/davechurchill/StarcraftAITournamentManager/files/3288971/vs2010_vcredist_x86-10.0.40219.325.exe.zip)
[vs2012_vcredist_x86-11.0.61030.0.exe.zip](https://github.com/davechurchill/StarcraftAITournamentManager/files/3288972/vs2012_vcredist_x86-11.0.61030.0.exe.zip)
[vs2013_vcredist_x86-12.0.30501.0.exe.zip](https://github.com/davechurchill/StarcraftAITournamentManager/files/3288973/vs2013_vcredist_x86-12.0.30501.0.exe.zip)
[vs2013_vcredist_x86-12.0.40664.0.exe.zip](https://github.com/davechurchill/StarcraftAITournamentManager/files/3288974/vs2013_vcredist_x86-12.0.40664.0.exe.zip)
[vs2015-2019_vc_redist.x86-14.21.27702.2.exe.zip](https://github.com/davechurchill/StarcraftAITournamentManager/files/3288966/vs2015-2019_vc_redist.x86-14.21.27702.2.exe.zip)

MD5 for ZIPs:
57aee1547c1fde55905577c6a135ae8b *install_redists.bat.zip
621e520ed120a635575b2fd9eb7c0948 *vs2008_vcredist_x86-9.0.21022.8.exe.zip
7295ce866c7cfc0f829ee70dd37bf212 *vs2008_vcredist_x86-9.0.30729.17.exe.zip
446fcb7c5e96f0db11a5bfdf5c8a4600 *vs2008_vcredist_x86-9.0.30729.6161.exe.zip
3cc2d5cbc7bf81cd9d0a67c7588a14e9 *vs2010_vcredist_x86-10.0.40219.325.exe.zip
3011b8df456f197466e4c23626e3e001 *vs2012_vcredist_x86-11.0.61030.0.exe.zip
eae8d4b35f850865e28c0ddaa101caf9 *vs2013_vcredist_x86-12.0.30501.0.exe.zip
7fa2342fc200d34fa99158491eaaf666 *vs2013_vcredist_x86-12.0.40664.0.exe.zip
c5bdf2614303718bf51cdd1716212db0 *vs2015-2019_vc_redist.x86-14.21.27702.2.exe.zip

SHA256 for ZIPs:
97accc35316b4c01b6b9dab43f7b5e06427f5f0ea580c73dd59bf79c2d07fce9 *install_redists.bat.zip
e2039e6e6f7e957e6a0f930319d199a9b6722a1791b8170386a3524c1203411a *vs2008_vcredist_x86-9.0.21022.8.exe.zip
520345c1412cd317f451569d4f65886a36b98e64f979d319522490e10859d91c *vs2008_vcredist_x86-9.0.30729.17.exe.zip
caeb12d8ffc119f6965003fc0e6e0c0341293233b812acb78192de73ac3202c2 *vs2008_vcredist_x86-9.0.30729.6161.exe.zip
2cb4b367d96f8f8decf69f556dfcf1b36fd95ad8680fe36a97d22c907ea58a4c *vs2010_vcredist_x86-10.0.40219.325.exe.zip
1456a9b0e9096b724af1d586dbc4bfc1f760b07a5747a4f15b5b9cbcc61f84f6 *vs2012_vcredist_x86-11.0.61030.0.exe.zip
f2d88480ba570d4a4adb26afa519b4bccb6f661c50524e7e8d4e335209275bf8 *vs2013_vcredist_x86-12.0.30501.0.exe.zip
bcf27c4b19baadba53a6efb85821aecd113c57192784a6d280a54019f031b0ec *vs2013_vcredist_x86-12.0.40664.0.exe.zip
e4512f0cae980f4fcfda03acaa25bd5b2b6a4443ea75cb370af77d550e2582c9 *vs2015-2019_vc_redist.x86-14.21.27702.2.exe.zip

MD5 for EXEs:
b936f0f378b9a35489353e878154e899 *vs2008_vcredist_x86-9.0.21022.8.exe
5689d43c3b201dd3810fa3bba4a6476a *vs2008_vcredist_x86-9.0.30729.17.exe
35da2bf2befd998980a495b6f4f55e60 *vs2008_vcredist_x86-9.0.30729.6161.exe
1801436936e64598bab5b87b37dc7f87 *vs2010_vcredist_x86-10.0.40219.325.exe
7f52a19ecaf7db3c163dd164be3e592e *vs2012_vcredist_x86-11.0.61030.0.exe
0fc525b6b7b96a87523daa7a0013c69d *vs2013_vcredist_x86-12.0.30501.0.exe
38a1b890ce847167d16567cf7b7a5642 *vs2013_vcredist_x86-12.0.40664.0.exe
ca1fb26a16d42fd8c48999769c98a385 *vs2015-2019_vc_redist.x86-14.21.27702.2.exe

SHA256 for EXEs:
c6a7e484f4d84883bc1205bccea3114c0521025712922298ede9b2a1cd632357 *vs2008_vcredist_x86-9.0.21022.8.exe
41f45a46ee56626ff2699d525bb56a3bb4718c5ca5f4fb5b3b38add64584026b *vs2008_vcredist_x86-9.0.30729.17.exe
6b3e4c51c6c0e5f68c8a72b497445af3dbf976394cbb62aa23569065c28deeb6 *vs2008_vcredist_x86-9.0.30729.6161.exe
67313b3d1bc86e83091e8de22981f14968f1a7fb12eb7ad467754c40cd94cc3d *vs2010_vcredist_x86-10.0.40219.325.exe
b924ad8062eaf4e70437c8be50fa612162795ff0839479546ce907ffa8d6e386 *vs2012_vcredist_x86-11.0.61030.0.exe
a22895e55b26202eae166838edbe2ea6aad00d7ea600c11f8a31ede5cbce2048 *vs2013_vcredist_x86-12.0.30501.0.exe
53b605d1100ab0a88b867447bbf9274b5938125024ba01f5105a9e178a3dcdbd *vs2013_vcredist_x86-12.0.40664.0.exe
3a43e8a55a3f3e4b73d01872c16d47a19dd825756784f4580187309e7d1fcb74 *vs2015-2019_vc_redist.x86-14.21.27702.2.exe

**Comment by richard-kelly** [comment]
Thanks for your work on this Chris! The current version hosted on the competition site and referenced in this project's readme has your latest up-to-date list.
