### ISSUE TITLE
Game Speed slider setting in game lobbies

### ISSUE THREAD

**Issue by chriscoxe** [davechurchill/StarcraftAITournamentManager#37]
From #31 point 3. I.E.:

> At least a few months before the competition (so we have time for sufficient training/testing), tell us in the [Rules page](https://www.cs.mun.ca/~dchurchill/starcraftaicomp/rules.shtml) whether the Game Speed slider in the game lobbies will be set to Normal or Fastest (i.e. LF3 or LF6 respectively). I added a feature request to BWAPI to make organizers' management easier for this (bwapi/bwapi#807). If you want to use "Fastest", I suggest you ask as early as possible whether there are any objections from the big teams like Facebook and Sumsung and other serious competitors, because bots that rely on ML training might need a lot of time/resources to be re-trained.

In the [Undermind podcast Episode 18](https://makingcomputerdothings.com/undermind-episode-18/) in the part from 51:03-54:32, Dave (with some comments from Antiga) replied to my question about whether AIIDE 2019 will set the Game Speed slider in the game lobbies to "Normal" or "Fastest".  Just need to clarify the [Rules page](https://www.cs.mun.ca/~dchurchill/starcraftaicomp/rules.shtml) similarly to how CIG worded their rules ([here](https://cilab.sejong.ac.kr/sc_competition/?cat=11)), depending on whether you want "Normal" or "Fastest", then this issue can be closed.

Background: In GitHub on StarcraftAITournamentManager's "ladder" branch, it's configurable and in the default config file, the "lobbyGameSpeed" setting is set to "Normal".  If last year's bots are re-entered (e.g. SAIDA and/or CherryPi if they don't get updated - note that Dave mentioned that CherryPi used trained models), AIIDE 2019 may want to stick with "Normal" in case last year's bot versions don't work properly using "Fastest".  E.g. CIG 2018 used "Fastest" and Overkill (re-entered without any update from the previous year) seemed to perform badly due to using "Fastest" (refer to the last comment at http://satirist.org/ai/starcraft/blog/archives/678-CIG-2018-Overkill-was-broken.html and http://satirist.org/ai/starcraft/blog/archives/686-CIG-2018-not-only-Overkill-was-broken.html).

**Comment by richard-kelly** [comment]
We are going to set it to "Normal", and that should be updated soon in the competition page.
