### ISSUE TITLE
Questions about Cherrypi

### ISSUE THREAD

**Issue by yuntao-ma** [davechurchill/StarcraftAITournamentManager#38]
We installed CUDA9.0 and corresponding CuDNN as you suggested and we tried to run Cherrypi again.  It still doesn't work and stuck like this.
![QQ图片20190626164033](https://user-images.githubusercontent.com/48904804/60165788-86de1980-9832-11e9-9e6b-4246d3a84374.jpg)
And if we run Cherrypi.exe straightly, there is an error printed on the screen.
![IMG_20190626_165928](https://user-images.githubusercontent.com/48904804/60166488-dffa7d00-9833-11e9-9e14-a0f0345e591d.jpg)
We don't know what's wrong with it. we appreciate it if you could tell us what to do next.

**Comment by davechurchill** [comment]
Sorry, but we do not have time to spend debugging individual bots. This is for the tournament manager software itself
