### ISSUE TITLE
Can't upload bot

### ISSUE THREAD

**Issue by dgant** [davechurchill/StarcraftAITournamentManager#39]
I attempted to upload PurpleWave.zip, which contained PurpleWave.jar and BWAPI.dll. But the upload fails, with  returning a HTTP 500 error

[PurpleWave.zip](https://github.com/davechurchill/StarcraftAITournamentManager/files/3351877/PurpleWave.zip)

**Comment by chriscoxe** [comment]
I'm guessing it was because since it is a proxy bot, a run_proxy.bat file needed to be uploaded within the ZIP file.
