### ISSUE TITLE
Game not started counted incorrectly

### ISSUE THREAD

**Issue by nbarriga** [davechurchill/StarcraftAITournamentManager#4]
If a game doesn't start (rare, but happens, the away client sometimes can't join the game) I believe it is counted as a crash for the bot that reports first, even though both report crashes (because in a normal game we assume whoever reports first crashed first).

I believe the proper solution is to reschedule the game.

**Comment by davechurchill** [comment]
If you want to write this feature in I will pull it

**Comment by nbarriga** [comment]
Sure, as soon as I have some time. I was merely writing it down here so I
don't forget.

**Comment by davechurchill** [comment]
Awesome, thanks for keeping it up to date!
