### ISSUE TITLE
Precompiled JARs

### ISSUE THREAD

**Issue by dgant** [davechurchill/StarcraftAITournamentManager#8]
Hello,

The Tournament Manager documentation at http://www.cs.mun.ca/~dchurchill/starcraftaicomp/tm.shtml#download and at https://www.youtube.com/watch?v=tl-nansNbsA mention that precompiled server and client JARs are available from this repository. This no longer seems to be the case.

Are the precompiled JARs available anywhere at the moment?

**Comment by dgant** [comment]
@richard-kelly added jars to the alpha branch :smiley:

**Comment by richard-kelly** [comment]
@dgant You saw it before I could respond :)

**Comment by davechurchill** [comment]
Also Dan just FYI making the jars is literally one click using the included .bat file :)
